# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [opened, synchronize, reopened]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew    
    - name: Cache SonarCloud packages
      uses: actions/cache@v1
      with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
    - name: Cache Gradle packages
      uses: actions/cache@v1
      with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
    - name: Build
      run: ./gradlew build --info
    - name: Sonar analyze 
      continue-on-error: true
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
      set +e
      ./gradlew sonarqube --info
      set -e
     
    - name: Publish on private
      env:
        PRIVATEREPOURL: ${{ secrets.PRIVATEREPOURL }}
        PRIVATEREPOUSER: ${{ secrets.PRIVATEREPOUSER }}
        PRIVATEREPOPASS: ${{ secrets.PRIVATEREPOPASS }}
      run: ./gradlew publishAllPublicationsToPrivateRepository --info
    - name: Publish on github
      env:
        PUBLISHTOKEN: ${{ secrets.PUBLISHTOKEN }}
      run: ./gradlew publishAllPublicationsToGithubRepository --info
